### ISSUE TITLE
Build a registration page

### ISSUE THREAD

**Issue by Scarly-Crow** [Scarly-Crow/lamia#9]
We should also have a registration page. Ideally it will have optional support for some kind of captcha. I'm not really sure which would be good to implement. I'm also pretty sure that we probably don't need to worry about this in 0.1.0 but if a captcha is low hanging fruit then...

Other than that

#### Implementation Steps

- [ ] POST /register
- [ ] GET / register
- [ ] Give an error if an account already exists with the same email
- [ ] Include a manual validation feature (i.e. a new account is added but not active until reviewed, email communications should clarify the status)
- [ ] Include a simple "Why do you want to join?" question and collect an answer (configured in lamia.config) 
- [ ] (Optional) Captcha support (configured in lamia.config)
- [ ] ???
- [ ] Socialism
